name:               Bot-BasicBot-Pluggable-Module-Puppet
version:            0.1
abstract:           Bot::BasicBot::Pluggable extension to turn your bot into a puppet
license:            perl
version_from:       lib/Bot/BasicBot/Pluggable/Module/Puppet.pm
installdirs:        site
distribution_type:  module
generated_by:       Mike Eldridge <diz@cpan.org>
author:
  - Mike Eldridge <diz@cpan.org>
